# SPDX-FileCopyrightText: 2023 - 2025 NeoN authors
#
# SPDX-License-Identifier: Unlicense

.build-and-test-neon-common:
  rules:
    # Run only when triggered via API
    - if: $CI_PIPELINE_SOURCE == "trigger" && $BENCHMARK != "true"
      when: always
    # Skip in all other cases
    - when: never

  before_script:
    # Install pre-commit
    - pip3 install --user --break-system-packages pre-commit
    - export PATH="$HOME/.local/bin:$PATH"

    # Optional: show versions of tools
    - cmake --version
    - clang++ --version || g++ --version

build-and-test-neon-nvidia:
  extends: .build-and-test-neon-common
  tags: ["nvidia-h100-gpus"]
  image: greole/neon-cuda
  script:
    - ./ci/build-and-test.sh nvidia

build-and-test-neon-amd:
  extends: .build-and-test-neon-common
  tags: ["amd-gpus"]
  image: chihtaw/neon-rocm:6.4.1-complete
  script:
    - ./ci/build-and-test.sh amd

.benchmark-neon-common:
  rules:
    # Run only when triggered via API for benchmarking
    - if: $CI_PIPELINE_SOURCE == "trigger" && $BENCHMARK == "true"
      when: always
    # Skip in all other cases
    - when: never

  variables:
    RESULTS_DIR: "benchmark-results"
    RUN_IDENTIFIER: "${CI_PIPELINE_ID}"
    REPO_NAME: "NeoFOAM-BenchmarkData"
    TARGET_REPO: "github.com/exasim-project/${REPO_NAME}.git"
    TARGET_BRANCH: "ci-benchmarks"

  before_script:
    # Install dependencies
    - pip3 install --user --break-system-packages xmltodict

benchmark-neon-nvidia:
  extends: .benchmark-neon-common
  tags: ["nvidia-h100-gpus"]
  image: greole/neon-cuda
  script:
    - ./ci/benchmark.sh nvidia

benchmark-neon-amd:
  extends: .benchmark-neon-common
  tags: ["amd-gpus"]
  image: chihtaw/neon-rocm:6.4.1-complete
  script:
    - ./ci/benchmark.sh amd
