repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v17.0.6'  # The default in Ubuntu 22.04, which is used in our CI
    hooks:
      - id: clang-format
        types_or: [c++]
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint
  - repo: https://github.com/fsfe/reuse-tool
    rev: v4.0.3
    hooks:
      - id: reuse
  - repo: https://github.com/crate-ci/typos
    rev: v1.23.1
    hooks:
      - id: typos
  - repo: local
    hooks:
      # The official reuse hook only supports calling lint, so we need our own hook
      # For MIT License
      - id: reuse-annotate-mit
        name: reuse-annotate-mit
        entry: reuse annotate --license MIT --copyright 'NeoN authors' --merge-copyright
        language: python
        additional_dependencies: [reuse==2.1.0]
        types_or: [c, c++, inc, python]
        # .cmake-format.py use Unlicense
        exclude: |
          (?x)^(
            .cmake-format.py|
            doc/conf.py|
            scripts/package.py|
          )$
      # For Unlicense
      - id: reuse-annotate-unlicense
        name: reuse-annotate-unlicense
        entry: reuse annotate --license Unlicense --copyright 'NeoN authors' --merge-copyright
        language: python
        require_serial: true
        additional_dependencies: [reuse==2.1.0]
        types_or: [cmake, python, gitignore, toml]
        # CPM.cmake from others. note: the current CPM.cmake can not be parsed by reuse annotate
        exclude: |
          (?x)^(
            REUSE.toml|
            scripts/package.py|
            scripts/catch2json.py|
            cmake/CPM.cmake
          )$
