name: Cancel LRZ GitLab pipelines

on:
  pull_request:
    types: [labeled]

jobs:
  cancel-lrz-ci:
    runs-on: ubuntu-latest
    # Only run if Skip-build label is present
    if: contains(toJson(github.event.pull_request.labels.*.name), 'Skip-build')

    steps:
      - name: Determine branch
        id: branch
        run: echo "branch=$GITHUB_HEAD_REF" >> $GITHUB_OUTPUT

      - name: Cancel running LRZ GitLab pipelines
        run: |
          BRANCH=${{ steps.branch.outputs.branch }}
          echo "Checking running pipelines on branch $BRANCH"

          pipelines=$(curl -s --header "PRIVATE-TOKEN: ${{ secrets.LRZ_GITLAB_TRIGGER_TOKEN }}" "https://gitlab-ce.lrz.de/api/v4/projects/greole%2Fneon/pipelines?ref=$BRANCH&status=running")

          echo "$pipelines" | jq -c '.[] | .id' | while read pid; do
            echo "Canceling pipeline $pid"
            curl -s --request POST --header "PRIVATE-TOKEN: ${{ secrets.LRZ_GITLAB_TRIGGER_TOKEN }}" "https://gitlab-ce.lrz.de/api/v4/projects/greole%2Fneon/pipelines/$pid/cancel"
          done
