name: LRZ GitLab CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  trigger-lrz-ci:
    name;: Trigger LRZ GitLab CI
    runs-on: ubuntu-latest
    if: "!contains(toJson(github.event.pull_request.labels.*.name), 'Skip-build')"
    steps:
      - name: Trigger LRZ GitLab CI pipeline
        id: trigger
        run: |
          echo "Triggering LRZ GitLab CI pipeline..."

          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            BRANCH="$GITHUB_HEAD_REF"
          else
            BRANCH=${GITHUB_REF_NAME#refs/heads/}
          fi

          echo "Triggering branch: $BRANCH"

          ENCODED_BRANCH=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$BRANCH'''))")
          echo "Encoded branch: $ENCODED_BRANCH"

          response=$(curl -s --request POST --form "token=${{ secrets.LRZ_GITLAB_TRIGGER_TOKEN }}" --form "ref=$ENCODED_BRANCH" "https://gitlab-ce.lrz.de/api/v4/projects/greole%2Fneon/trigger/pipeline")

          echo "$response" | jq .

          pipeline_id=$(echo "$response" | jq -r '.id')
          if [ "$pipeline_id" = "null" ]; then
            echo "Failed to trigger LRZ pipeline"
            exit 1
          fi

          echo "pipeline_id=$pipeline_id" >> $GITHUB_OUTPUT
