name: Trigger LRZ GitLab CI

on:
  push:
    branches: [dev, main]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  trigger-lrz-ci:
    name: Trigger LRZ GitLab CI
    runs-on: ubuntu-latest

    # Skip job if the PR has Skip-build label
    if: "!contains(toJson(github.event.pull_request.labels.*.name), 'Skip-build')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine branch
        id: branch
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" || "$GITHUB_EVENT_NAME" == "pull_request_target" ]]; then
            BRANCH="$GITHUB_HEAD_REF"
          else
            BRANCH=${GITHUB_REF_NAME#refs/heads/}
          fi
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Push commit to LRZ GitLab
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add lrz https://oauth2:${{ secrets.GITLAB_PAT }}@gitlab-ce.lrz.de/greole/neon.git
          git fetch origin ${{ steps.branch.outputs.branch }}
          git checkout -B ${{ steps.branch.outputs.branch }} origin/${{ steps.branch.outputs.branch }}
          git reset --hard origin/${{ steps.branch.outputs.branch }}
          git push --force lrz HEAD:refs/heads/${{ steps.branch.outputs.branch }}

      - name: Cancel running/pending LRZ GitLab pipelines
        run: |
          BRANCH=${{ steps.branch.outputs.branch }}
          echo "Canceling running/pending pipelines for branch $BRANCH"

          response=$(curl -s \
            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_PAT }}" \
            "https://gitlab-ce.lrz.de/api/v4/projects/greole%2Fneon/pipelines?ref=$BRANCH&order_by=id&sort=desc")

          echo "Raw response: $response"

          # Check if response is a valid JSON array
          if ! echo "$response" | jq -e 'type == "array"' >/dev/null; then
            echo "No pipelines found or unexpected response from GitLab API"
            exit 0
          fi

          # Filter only running or pending pipelines
          pipeline_ids=$(echo "$response" | jq -r '.[] | select(.status=="running" or .status=="pending") | .id')

          if [ -z "$pipeline_ids" ]; then
            echo "No running or pending pipelines to cancel for branch $BRANCH"
            exit 0
          fi

          for id in $pipeline_ids; do
            echo "Canceling pipeline $id"
            curl -s --request POST \
              --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_PAT }}" \
              "https://gitlab-ce.lrz.de/api/v4/projects/greole%2Fneon/pipelines/$id/cancel"
          done

      - name: Trigger LRZ GitLab pipeline
        id: trigger
        run: |
          BRANCH=${{ steps.branch.outputs.branch }}
          echo "Triggering new pipeline on branch $BRANCH"

          response=$(curl -s --request POST \
            --form "token=${{ secrets.LRZ_GITLAB_TRIGGER_TOKEN }}" \
            --form "ref=$BRANCH" \
            "https://gitlab-ce.lrz.de/api/v4/projects/greole%2Fneon/trigger/pipeline")

          echo "$response" | jq .

          pipeline_id=$(echo "$response" | jq -r '.id')
          if [ "$pipeline_id" = "null" ]; then
            echo "Failed to trigger LRZ pipeline"
            exit 1
          fi

          echo "pipeline_id=$pipeline_id" >> $GITHUB_OUTPUT
