name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare https://github.com/exasim-project/neon.git
      - run: cd neon.git && git push --mirror https://project_834_bot_6df5c61167fece4c7545b40648a987cb:${{ secrets.GITLAB_PAT }}@gitlab-ce.lrz.de/greole/neon.git
