name: On Comment
run-name: On Comment

on:
  pull_request:
    types:
      - comment
permissions:
  contents: write

jobs:
  Format:
    name: Format
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && github.event.comment.body == 'format!' && (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')
    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install \
           pre-commit
        pip install identify --upgrade
        pre-commit install

    - name: Run pre-commit on all files
      run: pre-commit run --all --color always --verbose || true

    - name: Add to PDF to repo
      run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add .
         git commit -m 'fix format'
         git push origin ${{ github.ref }}
