name: FoamAdapter LRZ GitLab CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      commit:
        required: true
        type: string

jobs:
  trigger-foamadapter:
    name: Trigger and run CI on GPU
    runs-on: ubuntu-latest

    steps:
      - name: Trigger FoamAdapter LRZ CI pipeline
        run: |
          echo "Triggering FoamAdapter CI pipeline for branch ${{ inputs.branch }} and commit ${{ inputs.commit }}"

          curl --fail --request POST \
            --form "token=${{ secrets.FOAMADAPTER_LRZ_GITLAB_TRIGGER_TOKEN }}" \
            --form "ref=main" \
            --form "variables[NEON_BRANCH]=${{ inputs.branch }}" \
            --form "variables[NEON_COMMIT]=${{ inputs.commit }}" \
            "https://gitlab-ce.lrz.de/api/v4/projects/1095/trigger/pipeline"
